### ISSUE TITLE
Dead link to example notebook

### ISSUE THREAD

**Issue by haesleinhuepf** [HenriquesLab/NanoPyx#106]
In the [readme, under Codeless example notebooks](https://github.com/HenriquesLab/NanoPyx?tab=readme-ov-file#codeless-jupyter-notebooks-available) the "Tutorial" / "Notebook" link leads to an error message: 404 Page not found

**Comment by brunomsaraiva** [comment]
Hi @haesleinhuepf, thanks for the catch, it is now fixed :)
