### ISSUE TITLE
interp2d is depreciated

### ISSUE THREAD

**Issue by paxcalpt** [HenriquesLab/NanoPyx#11]
We have to move away from interp2d, use one of ours instead

![image](https://user-images.githubusercontent.com/763757/214824385-c0d781f1-8033-4db4-b819-997b5b3878bd.png)

![image](https://user-images.githubusercontent.com/763757/214824102-a4977243-2a5d-4b58-b0c8-aeabcc305524.png)

**Comment by brunomsaraiva** [comment]
removed usage of interp2d
