### ISSUE TITLE
Release notes

### ISSUE THREAD

**Issue by haesleinhuepf** [HenriquesLab/NanoPyx#114]
Hi @antmsbrito 

I just saw that a new version was released. Awesome, congrats!

https://github.com/HenriquesLab/NanoPyx/releases/tag/0.5.0

Would it be possible to put release notes on that page so that people know what was changed? In particular consider listing backwards compatibility breaking changes. That can be key to maintain a good relationship with people who use nanopyx in their own work.

You can generate those notes when making the release (or later) by [clicking on the respective button](https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes) right next to the field where you enter the version number.

Thanks!

Best,
Robert

**Comment by antmsbrito** [comment]
All done!

Thanks,
AB
