### ISSUE TITLE
Add VirusMapper data to example data

### ISSUE THREAD

**Issue by antmsbrito** [HenriquesLab/NanoPyx#22]

**Comment by paxcalpt** [comment]
Done =)

Simply do...
``` python
from nanopyx.data.download import ExampleDataManager
z = downloader.get_ZipTiffIterator("VirusMapper_ViralParticles_Channel1", as_ndarray = True)
```
<img width="907" alt="image" src="https://user-images.githubusercontent.com/763757/217959433-6f2486a8-88b7-4b46-91d9-dec795a23524.png">

<img width="1210" alt="image" src="https://user-images.githubusercontent.com/763757/217959538-9e3b7a67-37f6-4b64-acf1-637d78d74c03.png">

Confirm it works on your end?

**Comment by antmsbrito** [comment]
Works good on my end!
