### ISSUE TITLE
No such file or directory: 'tests/_drift_table.npy' ..\venv-test\lib\site-packages\numpy\lib\npyio.py:518: FileNotFoundError

### ISSUE THREAD

**Issue by paxcalpt** [HenriquesLab/NanoPyx#24]
<img width="963" alt="image" src="https://user-images.githubusercontent.com/763757/217961872-11b10172-8eb7-44db-807e-f6d989288f25.png">

**Comment by paxcalpt** [comment]
Hi Bruno,

Would you mind reviewing this log and look into the drift_table path issues? Importantly, note that for the case in the log pytest is not being run in the root of the package (as in "pytest something/something/tests"), so the folder ./tests does not exist

[log (2).txt](https://github.com/HenriquesLab/NanoPyx/files/10702387/log.2.txt)

**Comment by brunomsaraiva** [comment]
Issue should now be fixed
