### ISSUE TITLE
appveyor pytest fail on decorrelation (windows)

### ISSUE THREAD

**Issue by paxcalpt** [HenriquesLab/NanoPyx#26]
[log (3).txt](https://github.com/HenriquesLab/NanoPyx/files/10823869/log.3.txt)

**Comment by paxcalpt** [comment]
![image](https://user-images.githubusercontent.com/763757/221175302-5d742989-9bd3-4143-a1af-10f904489763.png)

**Comment by paxcalpt** [comment]
it now breaks "math"

![image](https://user-images.githubusercontent.com/763757/221201629-5f8694b7-7cd9-4df1-8a73-8a7c8f344864.png)

![Uploading image.png…]()

**Comment by brunomsaraiva** [comment]
should now be solved
