### ISSUE TITLE
Why not use cython cos and sin instead?

### ISSUE THREAD

**Issue by paxcalpt** [HenriquesLab/NanoPyx#27]
https://github.com/HenriquesLab/NanoPyx/blob/6be3cb494ac59ccf4bc45352a051ebb324e3f21b/src/nanopyx/core/transform/interpolation/nearest_neighbor.pyx#L200

**Comment by antmsbrito** [comment]
Because after migrating to cython i forgot to change them =) Commit 0b384a763040d92084a7a0430706b00738f3a1c0 shoud fix it
