### ISSUE TITLE
Image loader in notebook unresponsive

### ISSUE THREAD

**Issue by grinic** [HenriquesLab/NanoPyx#84]
Hello,
I have installed nanopyx via `pip install nanopyx[all]` on a fresh environment, and download the ChannelRegistration notebook.
When I run the second cell (`Select which image to load`), the two loader buttons appear but are unresponsive. No error message appears.
Any idea how to fix it? Is there a package required that is not installed via `pip`?
Thank you very much for your help!

**Comment by brunomsaraiva** [comment]
Hi @grinic, thanks for opening this issue, we were just able to reproduce it calling the notebook using:
`jupyter lab`

However, calling the jupyter server with:
`jupyter notebook`
Is fully working for us. Could you please try it and report back whether that works for you?
In the meantime we'll be working on a fix for `jupyter lab` and will keep the issue open until we fix it

**Comment by grinic** [comment]
Hi @brunomsaraiva ,
thank you for your quick reply.
Indeed, when running `jupyter lab` I get the unresponsive buttons, but when I run `jupyter notebook` and open the notebook, I obtain a `Kernel error` message.
I then installed jupyter notebook with `pip install notebook` and run it again, but get the same unresponsive buttons.
I created the environment with:
`conda create -n nanopyx python=3.10`
`activate nanopyx`
`pip install nanopyx[all]`

**Comment by brunomsaraiva** [comment]
Hi, could you please tell me which OS and architecture(x86 or Arm64) you're using? Just so we can double check whether there was an issue with the compilation of the Python wheels in pypi.

**Comment by grinic** [comment]
I am on Windows 10, architecture AMD64

**Comment by brunomsaraiva** [comment]
Hi, sorry for the delay.
We just made a new release of the package and updated the notebooks, now everything should work both on jupyter lab and jupyter notebook.
I'll close the issue but feel free to open it if you find any other problems :)

**Comment by grinic** [comment]
Thanks for fixing it!
